name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 New'
      labels:
          - '✏️ Feature'
    - title: '🧹 Updates'
      labels:
          - '🧹 Updates'
          - '🤖 Dependencies'
    - title: '🐛 Fixes'
      labels:
          - '☢️ Bug'
    - title: '📚 Documentation'
      labels:
          - '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
            - '✏️ Feature'
    patch:
        labels:
            - 'patch'
            - '📒 Documentation'
            - '☢️ Bug'
            - '🤖 Dependencies'
            - '🧹 Updates'
    default: patch
autolabeler:
    - label: '📒 Documentation'
      title:
          - '/docs/i'
          - '/doc:/i'
          - '/\[doc\]/i'
          - '/README/i'
          - '/typos/i'
          - '/comment/i'
          - '/📚/i'
    - label: '☢️ Bug'
      branch:
          - '/fix\/.+/'
      title:
          - '/fix/i'
          - '/race/i'
          - '/bug/i'
          - '/🐛/i'
    - label: '🧹 Updates'
      title:
          - '/improve/i'
          - '/update/i'
          - '/refactor/i'
          - '/⚡/i'
          - '/🧹/i'
    - label: '🤖 Dependencies'
      title:
          - '/bumb/i'
          - '/dependencies/i'
    - label: '✏️ Feature'
      branch:
          - '/feature\/.+/'
      body:
          - '/feature/i'
          - '/add/i'
          - '/🚀/i'
template: |
    $CHANGES

    Thank you $CONTRIBUTORS for making this update possible.
